import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { NextRequest } from 'next/server'

export default function Home({ ip }) {
  // const [data, setData] = useState()

  useEffect(() => {
    const getData = async () => {
      const token =
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijg0YjYwMzQ1LTMyMmItNDQ2NC1iMDI5LTY3MmIwZTVmYjZiYiIsImlhdCI6MTY3MzYwNDAyMCwic3ViIjoiZGV2ZWxvcGVyLzgyMzBiMGZjLWE4MTUtNTA1Ni1mODhjLTAzZjBlMWY3Njg1ZCIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiMjEyLjc5LjExMC4xMTQiXSwidHlwZSI6ImNsaWVudCJ9XX0.ykVTigpILtS_wHXGPagIXBHIlzyyCbWYRuCf6HG1GF-n4NbBEJSZELQCCQR3TyvLO1l7fzTlaogWIhBkFmeyKA'
      const config = {
        headers: { Authorization: `Bearer ${token}` },
      }
      const url = 'https://api.brawlstars.com/v1/clubs/%23QOPPLRV/members'
      try {
        let res = await fetch(url, config)
        let data = await res.json()
        console.log('data', data)
      } catch (e) {
        console.log(e.message)
      }
    }
    getData()
  }, [])

  console.log('IP: ', ip)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Welcome to Brawlex</h1>
      {/* 
      #LLUVCYPLR
      #QOPPLRV 
      */}
    </>
  )
}

export async function getServerSideProps({ req }) {
  console.log(req.headers)
  const ip = req.headers['x-real-ip'] || req.connection.remoteAddress

  return {
    props: {
      ip,
    },
  }
}
